<?xml version="1.0" encoding="utf-8"?><Database Name="ShopSimple" Class="DBShopSimpleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TOAN\SQLSTUDY;Initial Catalog=ShopSimple;User ID=sa" SettingsObjectName="ShopSimple.Properties.Settings" SettingsPropertyName="ShopSimpleConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Username" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Association Name="Admin_Import" Member="Imports" ThisKey="Username" OtherKey="UserID" Type="Import" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Username" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="Username" OtherKey="UserID" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Catalog" Member="Catalogs">
    <Type Name="Catalog">
      <Column Name="CatalogCode" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Catalog_Product" Member="Products" ThisKey="CatalogCode" OtherKey="CatalogID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Phone" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Association Name="Customer_Invoice" Member="Invoices" ThisKey="Phone" OtherKey="CustomerPhone" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Import" Member="Imports">
    <Type Name="Import">
      <Column Name="ImportCode" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Import_ImportDetail" Member="ImportDetails" ThisKey="ImportCode" OtherKey="ImportID" Type="ImportDetail" />
      <Association Name="Admin_Import" Member="Admin" ThisKey="UserID" OtherKey="Username" Type="Admin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImportDetail" Member="ImportDetails">
    <Type Name="ImportDetail">
      <Column Name="ImportID" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Import_ImportDetail" Member="Import" ThisKey="ImportID" OtherKey="ImportCode" Type="Import" IsForeignKey="true" />
      <Association Name="Product_ImportDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductCode" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceCode" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerPhone" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceDetail" Member="InvoiceDetails" ThisKey="InvoiceCode" OtherKey="InvoiceID" Type="InvoiceDetail" />
      <Association Name="Customer_Invoice" Member="Customer" ThisKey="CustomerPhone" OtherKey="Phone" Type="Customer" IsForeignKey="true" />
      <Association Name="User_Invoice" Member="User" ThisKey="UserID" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceDetail" Member="InvoiceDetails">
    <Type Name="InvoiceDetail">
      <Column Name="InvoiceID" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceDetail" Member="Invoice" ThisKey="InvoiceID" OtherKey="InvoiceCode" Type="Invoice" IsForeignKey="true" />
      <Association Name="Product_InvoiceDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductCode" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CatalogID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Product_ImportDetail" Member="ImportDetails" ThisKey="ProductCode" OtherKey="ProductID" Type="ImportDetail" />
      <Association Name="Product_InvoiceDetail" Member="InvoiceDetails" ThisKey="ProductCode" OtherKey="ProductID" Type="InvoiceDetail" />
      <Association Name="Catalog_Product" Member="Catalog" ThisKey="CatalogID" OtherKey="CatalogCode" Type="Catalog" IsForeignKey="true" />
      <Association Name="Status_Product" Member="Status" ThisKey="StatusID" OtherKey="StatusCode" Type="Status" IsForeignKey="true" />
      <Association Name="Supplier_Product" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierCode" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="StatusCode" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Association Name="Status_Product" Member="Products" ThisKey="StatusCode" OtherKey="StatusID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierCode" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="Supplier_Product" Member="Products" ThisKey="SupplierCode" OtherKey="SupplierID" Type="Product" />
    </Type>
  </Table>
</Database>